### ISSUE TITLE
1.20.3 & 1.20.4 support

### ISSUE THREAD

**Issue by 10kmotorola** [JustAlittleWolf/elytraBugFix#2]
mod works fine for me on 1.20.4 so far :)

**Comment by JustAlittleWolf** [comment]
I am not sure what this is about, do you mean modrinth releases?

**Comment by 10kmotorola** [comment]
oh, yes, sorry. you can't add the mod to your installation when it doesnt list the version as supported. sorry for the confusion ^^"

**Comment by JustAlittleWolf** [comment]
This has been fixed! Thanks for reporting this :)
